<a href="https://colab.research.google.com/github/CODERVIPERSAN/ml_algorithm/blob/main2/ml_practice3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [461]:

#online learning

import pandas as pd
from sklearn.model_selection import train_test_split
train_test_split?

In [462]:
df = pd.read_csv("data_for_large_scale.csv")

In [463]:
X,y=df.drop("Target",axis=1),df.Target

In [464]:
X

Feature-1  Feature-2  Feature-3  Feature-4  Feature-5  Feature-6  \
0         -1.580     1.0500     1.0600     -0.440    0.45100    -0.0348   
1         -0.832    -0.8660    -1.3400      0.138    1.18000     0.7330   
2         -0.237     2.0900    -3.9300      0.296    0.35200    -0.5010   
3         -1.170    -1.1300    -1.0900      1.120    0.31200     0.1830   
4          0.260    -0.0273     0.9250     -1.150   -1.39000     0.0251   
...          ...        ...        ...        ...        ...        ...   
89995     -0.268    -0.3200    -0.0146     -0.251    1.76000     0.8590   
89996     -0.774     0.4960     1.9400      0.673    0.29500    -0.0137   
89997      0.509    -0.3220     0.6810     -0.276   -0.00553    -1.1000   
89998      0.360     1.2500     0.6510     -0.871    0.37900     0.7690   
89999     -0.860    -0.6010     0.7390      0.190   -0.33100    -1.2700   

       Feature-7  Feature-8  Feature-9  Feature-10  
0          0.643     0.2650      0.268     -0.8510  
1         -1.410     0.1350     -0.088     -1.5500  
2          0.961    -0.0287      1.820      0.9380  
3          0.448    -0.8190     -1.010     -1.0800  
4          0.627     0.0950     -0.280     -0.8480  
...          ...        ...        ...         ...  
89995     -1.090    -1.3800      1.760     -1.0900  
89996     -0.966    -0.6270     -0.113      0.0767  
89997      0.453     0.7270     -1.940     -2.0100  
89998      1.330    -0.3670     -1.280     -1.1000  
89999     -2.610    -0.4830     -1.380      1.1100  

[90000 rows x 10 columns]

In [465]:
X.columns

Index(['Feature-1', 'Feature-2', 'Feature-3', 'Feature-4', 'Feature-5',
       'Feature-6', 'Feature-7', 'Feature-8', 'Feature-9', 'Feature-10'],
      dtype='object')

In [466]:
y

0         84.70
1       -211.00
2        -96.90
3       -152.00
4        -57.70
          ...  
89995     -4.15
89996     63.50
89997    -80.20
89998    158.00
89999   -369.00
Name: Target, Length: 90000, dtype: float64

In [467]:
X_array= X.to_numpy()
y_array=y.to_numpy()

In [468]:
X_train,X_test,y_train,y_test = train_test_split(X_array,y_array,test_size=0.3,random_state=10)

In [469]:
X_train_r = X_train.reshape(-1,90,10)


In [470]:
y_train_r = y_train.reshape(-1,90,1)

In [471]:
y_train_r.shape,X_train_r.shape

((700, 90, 1), (700, 90, 10))

In [472]:
from sklearn.linear_model import SGDRegressor

sgd_regressor = SGDRegressor(random_state=10)

for i in range(X_train_r.shape[0]):
  sgd_regressor.partial_fit(X_train_r[i],y_train_r[i])
  if i==4:
    print(sgd_regressor.coef_[4])



/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

56.05563939842212


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

In [473]:
sgd_regressor.intercept_

array([-0.0054532])

In [474]:
simple = SGDRegressor(random_state=10)
simple.fit(X_train,y_train)

SGDRegressor(random_state=10)

In [475]:
simple.intercept_

array([-0.00491983])

In [476]:
sgd_regressor.intercept_

array([-0.0054532])

In [477]:
simple.coef_[2]

81.23127787635237

In [478]:
sgd_regressor.coef_

array([51.3212522 , 22.26535893, 81.23762868, 53.19615839, 76.46565732,
       71.47204651, 93.45092409, 51.92198178, 30.03910055, 40.95656774])

In [479]:
y_pred = sgd_regressor.predict(X_test)
y_pred

array([ -68.70388015, -142.95630528, -393.72957311, ..., -141.53746989,
        -54.33418274, -218.19557261])

In [480]:
from sklearn.metrics import r2_score
score = r2_score(y_test,y_pred)

In [481]:
score

0.9999919793766233

In [482]:
r2_score(y_test,simple.predict(X_test))

0.9999919983449691

In [483]:
sgd_regressor.coef_[4]

76.46565731934268

In [484]:
#next quesiton:

file_path="https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt"

df_iter = pd.read_csv(file_path,header=None,iterator=True,chunksize=20000)
columns = ["OSM_ID","LONGITUDE","LATITUDE","ALTITUDE"]



In [485]:
df = pd.concat(df_iter)

In [486]:
y=df.iloc[:,-1]

In [487]:
X=df.iloc[:,:-1]
X

0         1          2
0       144552912  9.349849  56.740876
1       144552912  9.350188  56.740679
2       144552912  9.350549  56.740544
3       144552912  9.350806  56.740485
4       144552912  9.351053  56.740486
...           ...       ...        ...
434869   93323205  9.936479  57.499686
434870   93323205  9.935696  57.499426
434871   93323205  9.935009  57.499282
434872   93323209  9.943479  57.495919
434873   93323209  9.943451  57.496270

[434874 rows x 3 columns]

In [488]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.3,random_state=10,shuffle=False)

In [489]:
X_train.to_csv("/content/train.csv",index=False,header=False)

In [490]:
df_iter1 = pd.read_csv("/content/train.csv",header=None,iterator=True,chunksize=20000)

In [491]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
for chunk in df_iter1:
  scalar.partial_fit(chunk)



In [492]:
from sklearn.linear_model import SGDRegressor

sgd2 = SGDRegressor(random_state=10)

In [493]:
import numpy as np
X_train_s =scalar.transform(X_train)

X_train_arr = np.array(X_train_s)
y_train_arr = np.array(y_train)
train_temp2 = X_train_arr[0:20000*15].reshape(-1,20000,3)
train_temp = X_train_arr[20000*15:]
test_temp2 = y_train_arr[0:20000*15].reshape(-1,20000,1)
test_temp = y_train_arr[20000*15:]

In [494]:
i=0
for chunk in train_temp2:
  print("Iteration:",i)
  sgd2.partial_fit(chunk,test_temp2[i])
  if(i==6):
    print("intercept:",sgd2.intercept_)
    print("weights:",sgd2.coef_)
  i+=1
else:
  print(i)
  sgd2.partial_fit(train_temp,test_temp)


Iteration: 0
Iteration: 1
Iteration: 2
Iteration: 3
Iteration: 4
Iteration: 5
Iteration: 6
intercept: [21.46794974]
weights: [-0.19400954  4.74439367 -5.13781446]
Iteration: 7
Iteration: 8
Iteration: 9
Iteration: 10
Iteration: 11
Iteration: 12
Iteration: 13
Iteration: 14
15


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam